### ISSUE TITLE
update-qstat operation fails

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/jobqueueing#13]
```
(env_climdex) hiebert@leopard:/local_temp/hiebert$ jq -d $JQ_DB update-qstat
Traceback (most recent call last):
  File "/local_temp/hiebert/env_climdex/bin/jq", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/storage/home/hiebert/code/git/jobqueueing/scripts/jq", line 239, in <module>
    exit_status = args.action(session, args)
  File "/storage/home/hiebert/code/git/jobqueueing/scripts/jq", line 128, in update_with_qstat
    return update(session)
  File "/storage/home/hiebert/code/git/jobqueueing/jobqueueing/gc_update_qstat.py", line 73, in update
    qstat_item = yaml.load(qstat_to_yaml(stdout.decode('utf-8')))[0]
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/local_temp/hiebert/env_climdex/lib64/python3.4/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 38, column 1:
    Unable to copy file /var/lib/tor ... 
    ^
could not find expected ':'
  in "<unicode string>", line 39, column 1:
    *** error from copy
    ^
```

**Comment by jameshiebert** [comment]
This problem just magically went away for me, so I'm not sure what's up with that. Python virtual environment problems. I don't know. Closing this issue.
